### ISSUE TITLE
Not possible to use \lstinline command inside \nota section

### ISSUE THREAD

**Issue by taihup** [mtzguido/lcc.cls#5]
I get an error with the following text:

\nota{Para setear los comandos de velocidad por un tiempo determinado se puede utilizar el comando \lstinline[style=bash]{ros2 topic pub} con los argumentos -1 y --keep-alive.}

The error thrown: ! Missing \endcsname inserted.

Everything is fine if I remove \lstinline command.

**Comment by mtzguido** [comment]
Hola Taihú.

`nota` es un entorno, hay que usarlo con begin/end, y para bash está el comando `\bash` para no tener que escribir `\lstinline` todo el tiempo (es simplemente un alias a `\lstinline[language=lcc_Bash]`).

Esto anda:
```latex
\begin{nota}
    Para setear los comandos de velocidad por un tiempo determinado se
    puede utilizar el comando \bash{ros2 topic pub} con los argumentos
    \bash{-1} y \bash{--keep-alive}.
\end{nota}
```
Puede ser que `\nota{..}` te ande porque no tiene "terminador", pero para `solucion` no te va a andar.

Aunque si te sirve creo que podría agregar un comando para notas más compacto... capaz algo así:
```latex
\newcommand{\notita}[1]{\begin{nota}#1\end{nota}}
```

Avisame cualquier cosa.

**Comment by taihup** [comment]
perfecto, lo uso con el \begin y \end entonces.... gracias @mtzguido!
